const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];

const categories = ["All", "Calculators", "Finance", "Measurements", "Engineering", "Date & Time", "Text", "Developer", "Generators"];

const tools = [
  { id:"percentage", name:"Percentage Calculator", category:"Calculators", icon:"%", description:"Percentages, change and reverse percentages.", popular:true },
  { id:"ratio", name:"Ratio Calculator", category:"Calculators", icon:"∶", description:"Simplify and compare ratios." },
  { id:"average", name:"Average Calculator", category:"Calculators", icon:"x̄", description:"Mean, median, minimum and maximum." },
  { id:"fraction", name:"Fraction ↔ Decimal", category:"Calculators", icon:"½", description:"Convert fractions, decimals and percentages." },
  { id:"proportion", name:"Proportion Solver", category:"Calculators", icon:"x", description:"Solve a : b = c : x." },
  { id:"grade", name:"Grade Percentage", category:"Calculators", icon:"A+", description:"Convert marks into a percentage." },
  { id:"pace", name:"Pace Calculator", category:"Calculators", icon:"◷", description:"Calculate pace from distance and time." },
  { id:"fuel", name:"Fuel Cost Calculator", category:"Calculators", icon:"↗", description:"Estimate trip fuel usage and cost." },
  { id:"bmi", name:"BMI Calculator", category:"Calculators", icon:"◎", description:"Calculate body mass index quickly." },
  { id:"bmr", name:"BMR Estimate", category:"Calculators", icon:"⚡", description:"Estimate daily basal energy use." },

  { id:"emi", name:"EMI Calculator", category:"Finance", icon:"₹", description:"Monthly loan payment and total interest.", popular:true },
  { id:"simple-interest", name:"Simple Interest", category:"Finance", icon:"%", description:"Principal, interest and final amount." },
  { id:"compound-interest", name:"Compound Interest", category:"Finance", icon:"↗", description:"Forecast compounded investment growth." },
  { id:"gst", name:"GST / VAT Calculator", category:"Finance", icon:"+", description:"Add or remove tax from an amount." },
  { id:"discount", name:"Discount Calculator", category:"Finance", icon:"−", description:"Sale price and money saved." },
  { id:"margin", name:"Profit Margin", category:"Finance", icon:"↑", description:"Profit and gross margin from cost and price." },
  { id:"markup", name:"Markup Calculator", category:"Finance", icon:"×", description:"Markup percentage from cost and selling price." },
  { id:"tip", name:"Tip Calculator", category:"Finance", icon:"☕", description:"Tip, total bill and split per person." },
  { id:"savings", name:"Savings Goal", category:"Finance", icon:"◇", description:"Monthly saving needed to reach a target." },
  { id:"roi", name:"ROI Calculator", category:"Finance", icon:"↗", description:"Return on investment percentage." },

  { id:"length", name:"Length Converter", category:"Measurements", icon:"↔", description:"Metric, imperial and nautical lengths.", popular:true },
  { id:"mass", name:"Mass Converter", category:"Measurements", icon:"kg", description:"Kilograms, pounds, ounces and more." },
  { id:"temperature", name:"Temperature Converter", category:"Measurements", icon:"°", description:"Celsius, Fahrenheit and Kelvin." },
  { id:"area", name:"Area Converter", category:"Measurements", icon:"□", description:"Square units, acres and hectares." },
  { id:"volume", name:"Volume Converter", category:"Measurements", icon:"▣", description:"Litres, gallons, cups and cubic units." },
  { id:"speed", name:"Speed Converter", category:"Measurements", icon:"→", description:"km/h, mph, knots and m/s." },
  { id:"pressure", name:"Pressure Converter", category:"Measurements", icon:"P", description:"Pa, kPa, bar, psi, atm and more." },
  { id:"energy", name:"Energy Converter", category:"Measurements", icon:"E", description:"Joules, Wh, kWh, BTU and calories." },
  { id:"power", name:"Power Converter", category:"Measurements", icon:"W", description:"Watts, kilowatts and horsepower." },
  { id:"torque", name:"Torque Converter", category:"Measurements", icon:"τ", description:"N·m, lb-ft and kgf·m." },
  { id:"angle", name:"Angle Converter", category:"Measurements", icon:"∠", description:"Degrees, radians, gradians and turns." },
  { id:"data-size", name:"Data Size Converter", category:"Measurements", icon:"GB", description:"Bytes, KB, MB, GB and TB." },
  { id:"time-units", name:"Time Unit Converter", category:"Measurements", icon:"⌚", description:"Seconds, minutes, hours, days and weeks." },
  { id:"frequency", name:"Frequency Converter", category:"Measurements", icon:"Hz", description:"Hz, kHz, MHz and GHz." },
  { id:"flow", name:"Flow Rate Converter", category:"Measurements", icon:"≈", description:"L/min, L/s, m³/h and GPM." },
  { id:"fuel-economy", name:"Fuel Economy Converter", category:"Measurements", icon:"⛽", description:"L/100 km, km/L and MPG." },

  { id:"battery", name:"Battery Runtime", category:"Engineering", icon:"▰", description:"Estimate runtime from battery energy and load.", popular:true },
  { id:"battery-energy", name:"Battery Energy", category:"Engineering", icon:"🔋", description:"Convert voltage and amp-hours to Wh and kWh." },
  { id:"ohms-law", name:"Ohm's Law", category:"Engineering", icon:"Ω", description:"Calculate voltage, current or resistance.", popular:true },
  { id:"electrical-power", name:"Electrical Power", category:"Engineering", icon:"⚡", description:"Calculate watts from voltage and current." },
  { id:"voltage-divider", name:"Voltage Divider", category:"Engineering", icon:"V", description:"Calculate divider output voltage." },
  { id:"series-resistance", name:"Series Resistance", category:"Engineering", icon:"Σ", description:"Total resistance for series resistors." },
  { id:"parallel-resistance", name:"Parallel Resistance", category:"Engineering", icon:"∥", description:"Equivalent parallel resistance." },
  { id:"electricity-cost", name:"Electricity Cost", category:"Engineering", icon:"kWh", description:"Energy use and operating cost." },
  { id:"gear-ratio", name:"Gear Ratio", category:"Engineering", icon:"⚙", description:"Gear ratio and output RPM." },
  { id:"wheel-speed", name:"Wheel Speed", category:"Engineering", icon:"◯", description:"Vehicle speed from tyre diameter and RPM." },
  { id:"rpm-rads", name:"RPM ↔ rad/s", category:"Engineering", icon:"↻", description:"Rotational speed conversion." },
  { id:"density", name:"Density Calculator", category:"Engineering", icon:"ρ", description:"Density from mass and volume." },
  { id:"force", name:"Force Calculator", category:"Engineering", icon:"F", description:"Force from mass and acceleration." },
  { id:"work-energy", name:"Work Calculator", category:"Engineering", icon:"J", description:"Mechanical work from force and distance." },
  { id:"heat-energy", name:"Heat Energy", category:"Engineering", icon:"ΔT", description:"Q = m·c·ΔT heat calculation." },

  { id:"age", name:"Age Calculator", category:"Date & Time", icon:"◷", description:"Find exact age from a birth date.", popular:true },
  { id:"date-diff", name:"Date Difference", category:"Date & Time", icon:"□", description:"Days and weeks between two dates." },
  { id:"date-add", name:"Add / Subtract Days", category:"Date & Time", icon:"+d", description:"Move a date forward or backward." },
  { id:"weekday", name:"Day of Week", category:"Date & Time", icon:"D", description:"Find the weekday for any date." },
  { id:"leap-year", name:"Leap Year Checker", category:"Date & Time", icon:"366", description:"Check whether a year has 366 days." },
  { id:"timestamp", name:"Unix Timestamp", category:"Date & Time", icon:"⌚", description:"Convert dates and Unix timestamps." },
  { id:"countdown", name:"Countdown Calculator", category:"Date & Time", icon:"⏳", description:"Time remaining until a date and time." },

  { id:"word-counter", name:"Word Counter", category:"Text", icon:"Aa", description:"Words, characters, lines and reading time.", popular:true },
  { id:"case", name:"Case Converter", category:"Text", icon:"aA", description:"Upper, lower, title and sentence case." },
  { id:"slug", name:"Slug Generator", category:"Text", icon:"/", description:"Turn text into clean URL slugs." },
  { id:"find-replace", name:"Find & Replace", category:"Text", icon:"↺", description:"Replace matching text instantly." },
  { id:"remove-duplicates", name:"Remove Duplicate Lines", category:"Text", icon:"≠", description:"Keep only unique lines." },
  { id:"sort-lines", name:"Sort Lines", category:"Text", icon:"AZ", description:"Alphabetically sort lines ascending or descending." },
  { id:"trim-lines", name:"Trim & Clean Text", category:"Text", icon:"⌫", description:"Trim lines and collapse extra blank space." },
  { id:"reverse-text", name:"Reverse Text", category:"Text", icon:"↩", description:"Reverse characters or line order." },
  { id:"text-repeat", name:"Text Repeater", category:"Text", icon:"×", description:"Repeat text a chosen number of times." },
  { id:"reading-time", name:"Reading Time", category:"Text", icon:"◴", description:"Estimate reading and speaking duration." },

  { id:"json", name:"JSON Formatter", category:"Developer", icon:"{}", description:"Format, validate and minify JSON.", popular:true },
  { id:"base64", name:"Base64", category:"Developer", icon:"64", description:"Encode or decode Base64 text." },
  { id:"url-codec", name:"URL Encoder / Decoder", category:"Developer", icon:"%", description:"Encode or decode URL components." },
  { id:"html-entities", name:"HTML Escape / Unescape", category:"Developer", icon:"<>" , description:"Convert special HTML characters safely." },
  { id:"number-base", name:"Number Base Converter", category:"Developer", icon:"01", description:"Binary, octal, decimal and hexadecimal." },
  { id:"color-converter", name:"HEX ↔ RGB", category:"Developer", icon:"#", description:"Convert web colors between HEX and RGB." },
  { id:"sha256", name:"SHA-256 Hash", category:"Developer", icon:"#", description:"Generate a SHA-256 digest in your browser." },
  { id:"uuid", name:"UUID Generator", category:"Developer", icon:"ID", description:"Generate RFC 4122 version 4 UUIDs." },
  { id:"jwt", name:"JWT Decoder", category:"Developer", icon:"JWT", description:"Decode JWT header and payload locally." },

  { id:"password", name:"Password Generator", category:"Generators", icon:"✦", description:"Generate strong random passwords.", popular:true },
  { id:"random", name:"Random Number", category:"Generators", icon:"#", description:"Generate random numbers in a range." },
  { id:"random-list", name:"Random List Picker", category:"Generators", icon:"?", description:"Choose one random item from a list." },
  { id:"coin", name:"Coin Flip", category:"Generators", icon:"◐", description:"Generate heads or tails." },
  { id:"dice", name:"Dice Roller", category:"Generators", icon:"⚄", description:"Roll multiple dice with custom sides." },
  { id:"pin", name:"PIN Generator", category:"Generators", icon:"••", description:"Generate secure numeric PINs." },
  { id:"lorem", name:"Lorem Ipsum", category:"Generators", icon:"¶", description:"Generate placeholder paragraphs." },
  { id:"random-color", name:"Random Color", category:"Generators", icon:"●", description:"Generate a random HEX and RGB color." }
];

let activeCategory = "All";
let searchTerm = "";
const grid = $("#toolsGrid");
const categoryTabs = $("#categoryTabs");
const search = $("#toolSearch");
const emptyState = $("#emptyState");
const modalBackdrop = $("#modalBackdrop");
const modalTitle = $("#modalTitle");
const modalCategory = $("#modalCategory");
const modalBody = $("#modalBody");

function escapeHTML(value = "") { return String(value).replace(/[&<>'"]/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch])); }
function fmt(n, max = 2) { return Number(n).toLocaleString(undefined, { maximumFractionDigits: max }); }
function n(id, root = modalBody) { return Number($("#" + id, root)?.value); }
function val(id, root = modalBody) { return $("#" + id, root)?.value ?? ""; }
function gcd(a,b){ a=Math.abs(Math.trunc(a)); b=Math.abs(Math.trunc(b)); while(b){[a,b]=[b,a%b];} return a||1; }
function showToast(text = "Copied") { const old=$(".copy-toast"); if(old) old.remove(); const el=document.createElement("div"); el.className="copy-toast"; el.textContent=text; document.body.append(el); setTimeout(()=>el.remove(),1500); }
async function copyText(text) { try { await navigator.clipboard.writeText(text); showToast(); } catch { showToast("Copy unavailable"); } }
function resultCard(label, value, note = "", extra = "") { const text=String(value); const compact=text.length>80||text.includes("\n"); return `<div class="result-card"><div class="result-label">${escapeHTML(label)}</div><div class="result-value ${compact?"result-text":""}">${escapeHTML(text)}</div>${note?`<div class="result-note">${escapeHTML(note)}</div>`:""}${extra}</div>`; }
function field(label, id, type="number", placeholder="", suffix="", value="") { return `<label class="field"><span class="field-label">${escapeHTML(label)}</span><div class="input-wrap"><input id="${id}" type="${type}" placeholder="${escapeHTML(placeholder)}" value="${escapeHTML(value)}" ${type==="number"?'step="any"':''}><span class="suffix">${escapeHTML(suffix)}</span></div></label>`; }
function selectField(label,id,options){ return `<label class="field"><span class="field-label">${escapeHTML(label)}</span><div class="input-wrap"><select id="${id}">${options.map(([v,t])=>`<option value="${escapeHTML(v)}">${escapeHTML(t)}</option>`).join("")}</select></div></label>`; }
function button(label="Calculate",id="runTool"){ return `<div class="action-row"><button class="primary-button" id="${id}" type="button">${escapeHTML(label)}</button></div>`; }
function textArea(label,id,placeholder=""){ return `<label class="field"><span class="field-label">${escapeHTML(label)}</span><textarea id="${id}" class="tool-input" placeholder="${escapeHTML(placeholder)}"></textarea></label>`; }
function mini(label,value){ return `<div class="mini-result"><span>${escapeHTML(label)}</span><strong>${escapeHTML(value)}</strong></div>`; }
function wireEnter(root, callback){ root.addEventListener("keydown",e=>{ if(e.key==="Enter" && e.target.tagName==="INPUT") callback(); }); }
function validNumbers(...xs){ return xs.every(Number.isFinite); }

function categorySlug(value=""){ return String(value).toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""); }
function renderTabs(){ categoryTabs.innerHTML=categories.map(c=>`<button class="category-tab ${c===activeCategory?"active":""}" data-category="${c}" data-cat="${categorySlug(c)}" role="tab">${c}</button>`).join(""); $$(".category-tab",categoryTabs).forEach(tab=>tab.onclick=()=>{activeCategory=tab.dataset.category;renderTabs();renderTools();}); }
function toolSlug(tool){ return ({"percentage":"percentage-calculator","ratio":"ratio-calculator","average":"average-calculator","fraction":"fraction-to-decimal","proportion":"proportion-solver","grade":"grade-percentage","pace":"pace-calculator","fuel":"fuel-cost-calculator","bmi":"bmi-calculator","bmr":"bmr-estimate","emi":"emi-calculator","simple-interest":"simple-interest","compound-interest":"compound-interest","gst":"gst-vat-calculator","discount":"discount-calculator","margin":"profit-margin","markup":"markup-calculator","tip":"tip-calculator","savings":"savings-goal","roi":"roi-calculator","length":"length-converter","mass":"mass-converter","temperature":"temperature-converter","area":"area-converter","volume":"volume-converter","speed":"speed-converter","pressure":"pressure-converter","energy":"energy-converter","power":"power-converter","torque":"torque-converter","angle":"angle-converter","data-size":"data-size-converter","time-units":"time-unit-converter","frequency":"frequency-converter","flow":"flow-rate-converter","fuel-economy":"fuel-economy-converter","battery":"battery-runtime-calculator","battery-energy":"battery-energy-calculator","ohms-law":"ohms-law","electrical-power":"electrical-power-calculator","voltage-divider":"voltage-divider-calculator","series-resistance":"series-resistance-calculator","parallel-resistance":"parallel-resistance-calculator","electricity-cost":"electricity-cost-calculator","gear-ratio":"gear-ratio-calculator","wheel-speed":"wheel-speed-calculator","rpm-rads":"rpm-to-radians-per-second","density":"density-calculator","force":"force-calculator","work-energy":"work-calculator","heat-energy":"heat-energy-calculator","age":"age-calculator","date-diff":"date-difference-calculator","date-add":"add-subtract-days","weekday":"day-of-week","leap-year":"leap-year-checker","timestamp":"unix-timestamp-converter","countdown":"countdown-calculator","word-counter":"word-counter","case":"case-converter","slug":"slug-generator","find-replace":"find-and-replace","remove-duplicates":"remove-duplicate-lines","sort-lines":"sort-lines","trim-lines":"trim-and-clean-text","reverse-text":"reverse-text","text-repeat":"text-repeater","reading-time":"reading-time","json":"json-formatter","base64":"base64-encoder-decoder","url-codec":"url-encoder-decoder","html-entities":"html-escape-unescape","number-base":"number-base-converter","color-converter":"hex-to-rgb","sha256":"sha-256-hash-generator","uuid":"uuid-generator","jwt":"jwt-decoder","password":"password-generator","random":"random-number-generator","random-list":"random-list-picker","coin":"coin-flip","dice":"dice-roller","pin":"pin-generator","lorem":"lorem-ipsum-generator","random-color":"random-color-generator"})[tool.id] || tool.id; }
function renderTools(){ const term=searchTerm.trim().toLowerCase(); const filtered=tools.filter(tool=>(activeCategory==="All"||tool.category===activeCategory)&&(!term||`${tool.name} ${tool.category} ${tool.description}`.toLowerCase().includes(term))); grid.innerHTML=filtered.map(tool=>`<a class="tool-card" href="tools/${toolSlug(tool)}/" data-tool="${tool.id}" data-cat="${categorySlug(tool.category)}" aria-label="Open ${escapeHTML(tool.name)}"><div class="tool-top"><div class="tool-icon">${escapeHTML(tool.icon)}</div><span class="tool-arrow">↗</span></div><div><h3>${escapeHTML(tool.name)}</h3><p>${escapeHTML(tool.description)}</p><div class="tag">${escapeHTML(tool.category)}</div></div></a>`).join(""); emptyState.hidden=filtered.length>0; }
function renderQuickLinks(){ const root=$("#quickLinks"); if(!root)return; root.innerHTML=tools.filter(t=>t.popular).slice(0,6).map(t=>`<a class="quick-chip" href="tools/${toolSlug(t)}/">${escapeHTML(t.name)}</a>`).join(""); }
function openTool(id){ const tool=tools.find(t=>t.id===id); if(!tool)return; modalTitle.textContent=tool.name;modalCategory.textContent=tool.category;$("#toolModal").dataset.cat=categorySlug(tool.category);modalBody.innerHTML="";renderToolUI(id,modalBody);modalBackdrop.hidden=false;document.body.style.overflow="hidden";setTimeout(()=>$("input, textarea, select",modalBody)?.focus(),50);history.replaceState(null,"",`#${id}`); }
function closeModal(){modalBackdrop.hidden=true;document.body.style.overflow="";history.replaceState(null,"",location.pathname+location.search);}
const closeModalButton=$("#closeModal");
if(closeModalButton) closeModalButton.onclick=closeModal;
if(modalBackdrop) modalBackdrop.onclick=e=>{if(e.target===modalBackdrop)closeModal();};
document.addEventListener("keydown",e=>{
  if(e.key==="Escape"&&modalBackdrop&&!modalBackdrop.hidden)closeModal();
  if(e.key==="/"&&search&&(!modalBackdrop||modalBackdrop.hidden)&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){e.preventDefault();search.focus();}
});

const converters = {
  length:{units:{m:["Meters",1],km:["Kilometers",1000],cm:["Centimeters",.01],mm:["Millimeters",.001],um:["Micrometers",1e-6],nm:["Nanometers",1e-9],mi:["Miles",1609.344],yd:["Yards",.9144],ft:["Feet",.3048],in:["Inches",.0254],nmi:["Nautical miles",1852]}},
  mass:{units:{kg:["Kilograms",1],g:["Grams",.001],mg:["Milligrams",1e-6],t:["Metric tonnes",1000],lb:["Pounds",.45359237],oz:["Ounces",.028349523125],st:["Stone",6.35029318]}},
  area:{units:{m2:["Square metres",1],km2:["Square kilometres",1e6],cm2:["Square centimetres",1e-4],ft2:["Square feet",.09290304],in2:["Square inches",.00064516],yd2:["Square yards",.83612736],acre:["Acres",4046.8564224],ha:["Hectares",10000]}},
  volume:{units:{l:["Litres",1],ml:["Millilitres",.001],m3:["Cubic metres",1000],cm3:["Cubic centimetres",.001],galUS:["US gallons",3.785411784],galUK:["UK gallons",4.54609],qt:["US quarts",.946352946],pt:["US pints",.473176473],cup:["US cups",.2365882365],floz:["US fl oz",.02957352956]}},
  speed:{units:{ms:["m/s",1],kmh:["km/h",1/3.6],mph:["mph",.44704],knot:["knots",.5144444444],fts:["ft/s",.3048]}},
  pressure:{units:{pa:["Pascal",1],kpa:["kPa",1000],mpa:["MPa",1e6],bar:["bar",100000],mbar:["mbar",100],psi:["psi",6894.757293],atm:["atmosphere",101325],torr:["Torr",133.322368]}},
  energy:{units:{j:["Joule",1],kj:["kJ",1000],mj:["MJ",1e6],wh:["Wh",3600],kwh:["kWh",3.6e6],cal:["calorie",4.184],kcal:["kcal",4184],btu:["BTU",1055.05585262]}},
  power:{units:{w:["Watt",1],kw:["Kilowatt",1000],mw:["Megawatt",1e6],hp:["Mechanical hp",745.69987158],ps:["Metric hp / PS",735.49875],btuh:["BTU/h",.29307107]}},
  torque:{units:{nm:["N·m",1],lbft:["lb-ft",1.3558179483],lbin:["lb-in",.112984829],kgfm:["kgf·m",9.80665]}},
  angle:{units:{deg:["Degrees",Math.PI/180],rad:["Radians",1],grad:["Gradians",Math.PI/200],turn:["Turns",2*Math.PI]}},
  "data-size":{units:{B:["Bytes",1],KB:["KB (decimal)",1e3],MB:["MB (decimal)",1e6],GB:["GB (decimal)",1e9],TB:["TB (decimal)",1e12],KiB:["KiB (binary)",1024],MiB:["MiB (binary)",1048576],GiB:["GiB (binary)",1073741824],TiB:["TiB (binary)",1099511627776]}},
  "time-units":{units:{s:["Seconds",1],min:["Minutes",60],h:["Hours",3600],d:["Days",86400],wk:["Weeks",604800],yr:["Years (365.25 d)",31557600]}},
  frequency:{units:{hz:["Hz",1],khz:["kHz",1e3],mhz:["MHz",1e6],ghz:["GHz",1e9],rpm:["RPM",1/60]}},
  flow:{units:{lmin:["L/min",1],ls:["L/s",60],m3h:["m³/h",1000/60],gpmUS:["US gal/min",3.785411784]}}
};
function genericConverter(id,root){const c=converters[id];const opts=Object.entries(c.units).map(([k,v])=>[k,v[0]]);root.innerHTML=`<div class="tool-form">${field("Value","convValue","number","1")}<div class="two-col">${selectField("From","convFrom",opts)}${selectField("To","convTo",opts)}</div>${button("Convert")}<div id="result"></div></div>`;const to=$("#convTo",root);if(opts[1])to.value=opts[1][0];const run=()=>{const x=n("convValue",root),from=val("convFrom",root),dest=val("convTo",root);if(!Number.isFinite(x))return;const out=x*c.units[from][1]/c.units[dest][1];$("#result",root).innerHTML=resultCard("Converted value",fmt(out,8),`${fmt(x,8)} ${from} = ${fmt(out,8)} ${dest}`);};$("#runTool",root).onclick=run;wireEnter(root,run);run();}

function simpleTool(root, html, run, auto=true){root.innerHTML=`<div class="tool-form">${html}${button()}<div id="result"></div></div>`;const fn=()=>{try{const r=run();if(!r)return;$("#result",root).innerHTML=resultCard(r.label||"Result",String(r.value),r.note||"",r.extra||"");}catch(e){$("#result",root).innerHTML=resultCard("Result","—",e.message||"Check your inputs.");}};$("#runTool",root).onclick=fn;wireEnter(root,fn);if(auto)fn();}
function listNumbers(text){return text.split(/[\s,;]+/).map(Number).filter(Number.isFinite);}

function renderToolUI(id,root){
  if(converters[id]) return genericConverter(id,root);
  const handlers={
    percentage(){root.innerHTML=`<div class="tool-form">${selectField("Calculation","pctMode",[["of","What is X% of Y?"],["change","Percentage change"],["is","X is what % of Y?"],["reverse","Y is X% of what?"]])}<div class="two-col">${field("First value","pctA","number","20")}${field("Second value","pctB","number","150")}</div>${button()}<div id="result"></div></div>`;const run=()=>{const a=n("pctA",root),b=n("pctB",root),m=val("pctMode",root);if(!validNumbers(a,b))return;let out,note;if(m==="of"){out=a/100*b;note=`${a}% of ${b}`;}if(m==="change"){if(a===0)return $("#result",root).innerHTML=resultCard("Result","Undefined","Starting value cannot be zero.");out=(b-a)/Math.abs(a)*100;note=`${b>=a?"Increase":"Decrease"} from ${a} to ${b}`;out=`${fmt(out,4)}%`;}if(m==="is"){if(b===0)return;out=`${fmt(a/b*100,4)}%`;note=`${a} as a percentage of ${b}`;}if(m==="reverse"){if(a===0)return;out=b/(a/100);note=`${b} is ${a}% of this value`;}$("#result",root).innerHTML=resultCard("Result",typeof out==="number"?fmt(out,6):out,note);};$("#runTool",root).onclick=run;wireEnter(root,run);run();},
    ratio(){simpleTool(root,`<div class="two-col">${field("A","ra","number","12")}${field("B","rb","number","18")}</div>`,()=>{const a=n("ra",root),b=n("rb",root);if(!validNumbers(a,b)||b===0)return;const d=gcd(a,b);return{value:`${a/d} : ${b/d}`,note:`Simplified from ${a} : ${b}`};});},
    average(){root.innerHTML=`<div class="tool-form">${textArea("Numbers","avgInput","12, 18, 25, 31")}${button("Calculate")}<div id="result"></div></div>`;const run=()=>{const xs=listNumbers(val("avgInput",root));if(!xs.length)return;const sorted=[...xs].sort((a,b)=>a-b),mean=xs.reduce((a,b)=>a+b,0)/xs.length,mid=Math.floor(sorted.length/2),median=sorted.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2;$("#result",root).innerHTML=resultCard("Average",fmt(mean,6),`${xs.length} values`,`<div class="mini-results">${mini("Median",fmt(median,6))}${mini("Minimum",fmt(sorted[0],6))}${mini("Maximum",fmt(sorted.at(-1),6))}${mini("Sum",fmt(xs.reduce((a,b)=>a+b,0),6))}</div>`);};$("#runTool",root).onclick=run;},
    fraction(){root.innerHTML=`<div class="tool-form">${selectField("Mode","fracMode",[["f2d","Fraction → decimal"],["d2f","Decimal → fraction"]])}<div id="fracFields"></div>${button("Convert")}<div id="result"></div></div>`;const render=()=>{$("#fracFields",root).innerHTML=val("fracMode",root)==="f2d"?`<div class="two-col">${field("Numerator","num","number","1")}${field("Denominator","den","number","4")}</div>`:field("Decimal","dec","number","0.25");};render();$("#fracMode",root).onchange=render;$("#runTool",root).onclick=()=>{if(val("fracMode",root)==="f2d"){const a=n("num",root),b=n("den",root);if(!validNumbers(a,b)||b===0)return;const d=a/b;$("#result",root).innerHTML=resultCard("Decimal",fmt(d,10),`${fmt(d*100,6)}%`);}else{const x=n("dec",root);if(!Number.isFinite(x))return;const precision=1e6;let a=Math.round(x*precision),b=precision,d=gcd(a,b);$("#result",root).innerHTML=resultCard("Fraction",`${a/d}/${b/d}`,`${fmt(x*100,6)}%`);}};},
    proportion(){simpleTool(root,`<div class="two-col">${field("A","pa","number","2")}${field("B","pb","number","5")}${field("C","pc","number","8")}</div>`,()=>{const a=n("pa",root),b=n("pb",root),c=n("pc",root);if(!validNumbers(a,b,c)||a===0)return;return{value:fmt(b*c/a,8),note:`${a} : ${b} = ${c} : x`};});},
    grade(){simpleTool(root,`<div class="two-col">${field("Marks earned","earned","number","82")}${field("Total marks","total","number","100")}</div>`,()=>{const e=n("earned",root),t=n("total",root);if(!validNumbers(e,t)||t<=0)return;return{value:`${fmt(e/t*100,2)}%`,note:`${fmt(e)} out of ${fmt(t)}`};});},
    pace(){simpleTool(root,`<div class="two-col">${field("Distance","paceD","number","5","km")}${field("Time","paceT","number","30","minutes")}</div>`,()=>{const d=n("paceD",root),t=n("paceT",root);if(!validNumbers(d,t)||d<=0||t<=0)return;const p=t/d;return{value:`${Math.floor(p)}:${String(Math.round((p%1)*60)).padStart(2,"0")} min/km`,note:`Average speed ${fmt(d/(t/60),2)} km/h`};});},
    fuel(){simpleTool(root,`<div class="two-col">${field("Distance","fuelDistance","number","350","km")}${field("Consumption","fuelEff","number","8","L/100 km")}${field("Fuel price","fuelPrice","number","3","per L")}</div>`,()=>{const d=n("fuelDistance",root),e=n("fuelEff",root),p=n("fuelPrice",root);if(!validNumbers(d,e,p))return;const litres=d*e/100;return{value:fmt(litres*p,2),note:`${fmt(litres,2)} L estimated fuel use`};});},
    bmi(){simpleTool(root,`<div class="two-col">${field("Weight","bmiW","number","70","kg")}${field("Height","bmiH","number","175","cm")}</div>`,()=>{const w=n("bmiW",root),h=n("bmiH",root)/100;if(!validNumbers(w,h)||h<=0)return;const x=w/(h*h);const c=x<18.5?"Underweight":x<25?"Typical range":x<30?"Overweight range":"High range";return{value:fmt(x,1),note:`${c}. BMI is a screening metric, not a diagnosis.`};});},
    bmr(){root.innerHTML=`<div class="tool-form">${selectField("Sex used by formula","bmrSex",[["m","Male"],["f","Female"]])}<div class="two-col">${field("Age","bmrAge","number","30","years")}${field("Weight","bmrW","number","70","kg")}${field("Height","bmrH","number","175","cm")}</div>${button("Estimate")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const age=n("bmrAge",root),w=n("bmrW",root),h=n("bmrH",root),sex=val("bmrSex",root);if(!validNumbers(age,w,h))return;const out=10*w+6.25*h-5*age+(sex==="m"?5:-161);$("#result",root).innerHTML=resultCard("Estimated BMR",`${fmt(out,0)} kcal/day`,"Mifflin–St Jeor estimate; individual needs vary.");};},

    emi(){simpleTool(root,`<div class="two-col">${field("Loan amount","emiP","number","100000")}${field("Annual interest","emiR","number","8","%")}${field("Term","emiY","number","5","years")}</div>`,()=>{const p=n("emiP",root),annual=n("emiR",root),years=n("emiY",root);if(!validNumbers(p,annual,years)||p<0||years<=0)return;const months=years*12,r=annual/1200;const emi=r===0?p/months:p*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1),total=emi*months;return{value:fmt(emi,2),note:"Estimated monthly payment",extra:`<div class="mini-results">${mini("Total paid",fmt(total,2))}${mini("Interest",fmt(total-p,2))}</div>`};});},
    "simple-interest"(){simpleTool(root,`<div class="two-col">${field("Principal","siP","number","10000")}${field("Annual rate","siR","number","5","%")}${field("Time","siT","number","3","years")}</div>`,()=>{const p=n("siP",root),r=n("siR",root),t=n("siT",root);if(!validNumbers(p,r,t))return;const i=p*r*t/100;return{value:fmt(i,2),note:"Interest",extra:`<div class="mini-results">${mini("Final amount",fmt(p+i,2))}${mini("Principal",fmt(p,2))}</div>`};});},
    "compound-interest"(){root.innerHTML=`<div class="tool-form"><div class="two-col">${field("Principal","ciP","number","10000")}${field("Annual rate","ciR","number","7","%")}${field("Years","ciY","number","10")}${selectField("Compounding","ciN",[["1","Yearly"],["4","Quarterly"],["12","Monthly"],["365","Daily"]])}</div>${button()}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const p=n("ciP",root),r=n("ciR",root)/100,y=n("ciY",root),q=n("ciN",root);if(!validNumbers(p,r,y,q))return;const a=p*Math.pow(1+r/q,q*y);$("#result",root).innerHTML=resultCard("Future value",fmt(a,2),`Growth ${fmt(a-p,2)}`);};},
    gst(){root.innerHTML=`<div class="tool-form">${selectField("Mode","taxMode",[["add","Add tax"],["remove","Remove included tax"]])}<div class="two-col">${field("Amount","taxAmount","number","1000")}${field("Tax rate","taxRate","number","18","%")}</div>${button()}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const a=n("taxAmount",root),r=n("taxRate",root)/100,m=val("taxMode",root);if(!validNumbers(a,r))return;const base=m==="add"?a:a/(1+r),tax=m==="add"?a*r:a-base,total=m==="add"?a+tax:a;$("#result",root).innerHTML=resultCard("Total",fmt(total,2),`Tax ${fmt(tax,2)}`,`<div class="mini-results">${mini("Net amount",fmt(base,2))}${mini("Tax",fmt(tax,2))}</div>`);};},
    discount(){simpleTool(root,`<div class="two-col">${field("Original price","discP","number","100")}${field("Discount","discR","number","20","%")}</div>`,()=>{const p=n("discP",root),r=n("discR",root);if(!validNumbers(p,r))return;const saved=p*r/100;return{value:fmt(p-saved,2),note:`You save ${fmt(saved,2)}`};});},
    margin(){simpleTool(root,`<div class="two-col">${field("Cost","marC","number","60")}${field("Selling price","marS","number","100")}</div>`,()=>{const c=n("marC",root),s=n("marS",root);if(!validNumbers(c,s)||s===0)return;return{value:`${fmt((s-c)/s*100,2)}%`,note:`Profit ${fmt(s-c,2)}`};});},
    markup(){simpleTool(root,`<div class="two-col">${field("Cost","markC","number","60")}${field("Selling price","markS","number","100")}</div>`,()=>{const c=n("markC",root),s=n("markS",root);if(!validNumbers(c,s)||c===0)return;return{value:`${fmt((s-c)/c*100,2)}%`,note:`Profit ${fmt(s-c,2)}`};});},
    tip(){simpleTool(root,`<div class="two-col">${field("Bill","tipBill","number","100")}${field("Tip","tipRate","number","15","%")}${field("People","tipPeople","number","2")}</div>`,()=>{const b=n("tipBill",root),r=n("tipRate",root),p=n("tipPeople",root);if(!validNumbers(b,r,p)||p<=0)return;const tip=b*r/100,total=b+tip;return{value:fmt(total/p,2),note:"Per person",extra:`<div class="mini-results">${mini("Tip",fmt(tip,2))}${mini("Total",fmt(total,2))}</div>`};});},
    savings(){simpleTool(root,`<div class="two-col">${field("Target","savTarget","number","12000")}${field("Already saved","savNow","number","2000")}${field("Months","savMonths","number","10")}</div>`,()=>{const t=n("savTarget",root),s=n("savNow",root),m=n("savMonths",root);if(!validNumbers(t,s,m)||m<=0)return;return{value:fmt(Math.max(0,t-s)/m,2),note:"Required per month, ignoring interest"};});},
    roi(){simpleTool(root,`<div class="two-col">${field("Initial investment","roiI","number","10000")}${field("Final value","roiF","number","12500")}</div>`,()=>{const i=n("roiI",root),f=n("roiF",root);if(!validNumbers(i,f)||i===0)return;return{value:`${fmt((f-i)/i*100,2)}%`,note:`Net gain ${fmt(f-i,2)}`};});},

    temperature(){root.innerHTML=`<div class="tool-form">${field("Value","tempValue","number","25")}<div class="two-col">${selectField("From","tempFrom",[["c","Celsius"],["f","Fahrenheit"],["k","Kelvin"]])}${selectField("To","tempTo",[["f","Fahrenheit"],["c","Celsius"],["k","Kelvin"]])}</div>${button("Convert")}<div id="result"></div></div>`;const run=()=>{const x=n("tempValue",root),f=val("tempFrom",root),t=val("tempTo",root);if(!Number.isFinite(x))return;const c=f==="c"?x:f==="f"?(x-32)*5/9:x-273.15;const out=t==="c"?c:t==="f"?c*9/5+32:c+273.15;$("#result",root).innerHTML=resultCard("Converted value",fmt(out,6),`${x}° ${f.toUpperCase()} → ${fmt(out,6)}° ${t.toUpperCase()}`);};$("#runTool",root).onclick=run;run();},
    "fuel-economy"(){root.innerHTML=`<div class="tool-form">${selectField("From","feMode",[["l100","L/100 km"],["kml","km/L"],["mpgus","MPG (US)"],["mpguk","MPG (UK)"]])}${field("Value","feValue","number","8")}${button("Convert")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const x=n("feValue",root),m=val("feMode",root);if(!Number.isFinite(x)||x<=0)return;const l100=m==="l100"?x:m==="kml"?100/x:m==="mpgus"?235.214583/x:282.480936/x;$("#result",root).innerHTML=resultCard("L/100 km",fmt(l100,4),"Equivalent values",`<div class="mini-results">${mini("km/L",fmt(100/l100,4))}${mini("MPG US",fmt(235.214583/l100,4))}${mini("MPG UK",fmt(282.480936/l100,4))}</div>`);};},

    battery(){simpleTool(root,`<div class="two-col">${field("Battery energy","batE","number","1000","Wh")}${field("Load","batP","number","100","W")}${field("Usable capacity","batU","number","90","%")}</div>`,()=>{const e=n("batE",root),p=n("batP",root),u=n("batU",root)/100;if(!validNumbers(e,p,u)||p<=0)return;const h=e*u/p;return{value:`${fmt(h,2)} hours`,note:`≈ ${fmt(h*60,0)} minutes`};});},
    "battery-energy"(){simpleTool(root,`<div class="two-col">${field("Voltage","beV","number","48","V")}${field("Capacity","beAh","number","100","Ah")}</div>`,()=>{const v=n("beV",root),ah=n("beAh",root);if(!validNumbers(v,ah))return;const wh=v*ah;return{value:`${fmt(wh,2)} Wh`,note:`${fmt(wh/1000,4)} kWh`};});},
    "ohms-law"(){root.innerHTML=`<div class="tool-form">${selectField("Solve for","ohmSolve",[["v","Voltage"],["i","Current"],["r","Resistance"]])}<div id="ohmFields"></div>${button()}<div id="result"></div></div>`;const render=()=>{const s=val("ohmSolve",root);$("#ohmFields",root).innerHTML=s==="v"?`<div class="two-col">${field("Current","ohmI","number","2","A")}${field("Resistance","ohmR","number","10","Ω")}</div>`:s==="i"?`<div class="two-col">${field("Voltage","ohmV","number","24","V")}${field("Resistance","ohmR","number","12","Ω")}</div>`:`<div class="two-col">${field("Voltage","ohmV","number","24","V")}${field("Current","ohmI","number","2","A")}</div>`;};render();$("#ohmSolve",root).onchange=render;$("#runTool",root).onclick=()=>{const s=val("ohmSolve",root);let out,unit;if(s==="v"){out=n("ohmI",root)*n("ohmR",root);unit="V";}if(s==="i"){out=n("ohmV",root)/n("ohmR",root);unit="A";}if(s==="r"){out=n("ohmV",root)/n("ohmI",root);unit="Ω";}if(!Number.isFinite(out))return;$("#result",root).innerHTML=resultCard("Result",`${fmt(out,6)} ${unit}`);};},
    "electrical-power"(){simpleTool(root,`<div class="two-col">${field("Voltage","epV","number","230","V")}${field("Current","epI","number","10","A")}${field("Power factor","epPf","number","1")}</div>`,()=>{const v=n("epV",root),i=n("epI",root),pf=n("epPf",root);if(!validNumbers(v,i,pf))return;const p=v*i*pf;return{value:`${fmt(p,2)} W`,note:`${fmt(p/1000,4)} kW`};});},
    "voltage-divider"(){simpleTool(root,`<div class="two-col">${field("Input voltage","vdV","number","12","V")}${field("R1","vdR1","number","10000","Ω")}${field("R2","vdR2","number","10000","Ω")}</div>`,()=>{const v=n("vdV",root),r1=n("vdR1",root),r2=n("vdR2",root);if(!validNumbers(v,r1,r2)||r1+r2===0)return;return{value:`${fmt(v*r2/(r1+r2),6)} V`,note:"Vout across R2"};});},
    "series-resistance"(){root.innerHTML=`<div class="tool-form">${textArea("Resistor values (Ω)","rsInput","100, 220, 470")}${button("Calculate")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const xs=listNumbers(val("rsInput",root));if(!xs.length)return;$("#result",root).innerHTML=resultCard("Equivalent resistance",`${fmt(xs.reduce((a,b)=>a+b,0),6)} Ω`,`${xs.length} resistors in series`);};},
    "parallel-resistance"(){root.innerHTML=`<div class="tool-form">${textArea("Resistor values (Ω)","rpInput","100, 220, 470")}${button("Calculate")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const xs=listNumbers(val("rpInput",root)).filter(x=>x>0);if(!xs.length)return;const r=1/xs.reduce((s,x)=>s+1/x,0);$("#result",root).innerHTML=resultCard("Equivalent resistance",`${fmt(r,6)} Ω`,`${xs.length} resistors in parallel`);};},
    "electricity-cost"(){simpleTool(root,`<div class="two-col">${field("Load","ecP","number","1500","W")}${field("Hours per day","ecH","number","4")}${field("Days","ecD","number","30")}${field("Price per kWh","ecC","number","0.30")}</div>`,()=>{const p=n("ecP",root),h=n("ecH",root),d=n("ecD",root),c=n("ecC",root);if(!validNumbers(p,h,d,c))return;const kwh=p/1000*h*d;return{value:fmt(kwh*c,2),note:`${fmt(kwh,2)} kWh consumed`};});},
    "gear-ratio"(){simpleTool(root,`<div class="two-col">${field("Input gear teeth","grIn","number","20")}${field("Output gear teeth","grOut","number","60")}${field("Input RPM","grRpm","number","3000")}</div>`,()=>{const a=n("grIn",root),b=n("grOut",root),rpm=n("grRpm",root);if(!validNumbers(a,b,rpm)||a<=0||b<=0)return;const ratio=b/a;return{value:`${fmt(ratio,4)} : 1`,note:`Output speed ${fmt(rpm/ratio,2)} RPM`};});},
    "wheel-speed"(){simpleTool(root,`<div class="two-col">${field("Tyre diameter","wsD","number","0.7","m")}${field("Wheel RPM","wsR","number","500")}</div>`,()=>{const d=n("wsD",root),rpm=n("wsR",root);if(!validNumbers(d,rpm))return;const kmh=Math.PI*d*rpm*60/1000;return{value:`${fmt(kmh,3)} km/h`,note:`${fmt(kmh/1.609344,3)} mph`};});},
    "rpm-rads"(){root.innerHTML=`<div class="tool-form">${selectField("Mode","rpmMode",[["r2w","RPM → rad/s"],["w2r","rad/s → RPM"]])}${field("Value","rpmValue","number","3000")}${button("Convert")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const x=n("rpmValue",root),m=val("rpmMode",root);if(!Number.isFinite(x))return;const out=m==="r2w"?x*2*Math.PI/60:x*60/(2*Math.PI);$("#result",root).innerHTML=resultCard("Converted value",`${fmt(out,6)} ${m==="r2w"?"rad/s":"RPM"}`);};},
    density(){simpleTool(root,`<div class="two-col">${field("Mass","denM","number","10","kg")}${field("Volume","denV","number","0.01","m³")}</div>`,()=>{const m=n("denM",root),v=n("denV",root);if(!validNumbers(m,v)||v===0)return;return{value:`${fmt(m/v,6)} kg/m³`};});},
    force(){simpleTool(root,`<div class="two-col">${field("Mass","forceM","number","100","kg")}${field("Acceleration","forceA","number","9.80665","m/s²")}</div>`,()=>{const m=n("forceM",root),a=n("forceA",root);if(!validNumbers(m,a))return;return{value:`${fmt(m*a,6)} N`};});},
    "work-energy"(){simpleTool(root,`<div class="two-col">${field("Force","workF","number","100","N")}${field("Distance","workD","number","5","m")}</div>`,()=>{const f=n("workF",root),d=n("workD",root);if(!validNumbers(f,d))return;return{value:`${fmt(f*d,6)} J`};});},
    "heat-energy"(){simpleTool(root,`<div class="two-col">${field("Mass","heatM","number","1","kg")}${field("Specific heat","heatC","number","4186","J/kg·K")}${field("Temperature change","heatT","number","10","K")}</div>`,()=>{const m=n("heatM",root),c=n("heatC",root),dt=n("heatT",root);if(!validNumbers(m,c,dt))return;const q=m*c*dt;return{value:`${fmt(q,4)} J`,note:`${fmt(q/1000,4)} kJ`};});},

    age(){root.innerHTML=`<div class="tool-form">${field("Date of birth","dob","date")}${field("Calculate age on","ageOn","date","","",new Date().toISOString().slice(0,10))}${button()}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const b=new Date(val("dob",root)+"T00:00:00"),e=new Date(val("ageOn",root)+"T00:00:00");if(isNaN(b)||isNaN(e)||e<b)return;let y=e.getFullYear()-b.getFullYear(),m=e.getMonth()-b.getMonth(),d=e.getDate()-b.getDate();if(d<0){m--;d+=new Date(e.getFullYear(),e.getMonth(),0).getDate();}if(m<0){y--;m+=12;}const days=Math.floor((e-b)/86400000);$("#result",root).innerHTML=resultCard("Age",`${y} years, ${m} months, ${d} days`,`${fmt(days,0)} total days`);};},
    "date-diff"(){simpleTool(root,`<div class="two-col">${field("Start date","ddStart","date")}${field("End date","ddEnd","date")}</div>`,()=>{const a=new Date(val("ddStart",root)+"T00:00:00"),b=new Date(val("ddEnd",root)+"T00:00:00");if(isNaN(a)||isNaN(b))return;const days=Math.round(Math.abs(b-a)/86400000);return{value:`${fmt(days,0)} days`,note:`${fmt(days/7,2)} weeks`};},false);},
    "date-add"(){root.innerHTML=`<div class="tool-form">${field("Starting date","daDate","date","","",new Date().toISOString().slice(0,10))}${field("Days to add (negative subtracts)","daDays","number","30")}${button("Calculate date")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const d=new Date(val("daDate",root)+"T00:00:00"),days=n("daDays",root);if(isNaN(d)||!Number.isFinite(days))return;d.setDate(d.getDate()+days);$("#result",root).innerHTML=resultCard("Result date",d.toLocaleDateString(undefined,{weekday:"long",year:"numeric",month:"long",day:"numeric"}));};},
    weekday(){root.innerHTML=`<div class="tool-form">${field("Date","wdDate","date")}${button("Find weekday")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const d=new Date(val("wdDate",root)+"T00:00:00");if(isNaN(d))return;$("#result",root).innerHTML=resultCard("Day of week",d.toLocaleDateString(undefined,{weekday:"long"}),d.toLocaleDateString());};},
    "leap-year"(){simpleTool(root,field("Year","lyYear","number",String(new Date().getFullYear())),()=>{const y=Math.trunc(n("lyYear",root));if(!Number.isFinite(y))return;const yes=y%4===0&&(y%100!==0||y%400===0);return{value:yes?"Leap year":"Not a leap year",note:yes?"366 days":"365 days"};});},
    timestamp(){const now=Math.floor(Date.now()/1000);root.innerHTML=`<div class="tool-form">${selectField("Convert","tsMode",[["to-date","Timestamp → Date"],["to-ts","Date → Timestamp"]])}<div id="tsField"></div>${button("Convert")}<div id="result"></div></div>`;const render=()=>{$("#tsField",root).innerHTML=val("tsMode",root)==="to-date"?field("Unix timestamp","tsValue","number",String(now)):field("Date and time","dateTime","datetime-local","","",new Date().toISOString().slice(0,16));};render();$("#tsMode",root).onchange=render;$("#runTool",root).onclick=()=>{if(val("tsMode",root)==="to-date"){const x=n("tsValue",root),d=new Date(x*(String(Math.trunc(x)).length>10?1:1000));if(isNaN(d))return;$("#result",root).innerHTML=resultCard("Date",d.toLocaleString(),d.toISOString());}else{const d=new Date(val("dateTime",root));if(isNaN(d))return;$("#result",root).innerHTML=resultCard("Unix timestamp",String(Math.floor(d.getTime()/1000)),"Seconds since 1 January 1970 UTC");}};},
    countdown(){root.innerHTML=`<div class="tool-form">${field("Target date & time","cdTarget","datetime-local")}${button("Calculate")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const t=new Date(val("cdTarget",root));if(isNaN(t))return;let ms=t-Date.now(),past=ms<0;ms=Math.abs(ms);const days=Math.floor(ms/86400000);ms%=86400000;const hours=Math.floor(ms/3600000);ms%=3600000;const mins=Math.floor(ms/60000);$("#result",root).innerHTML=resultCard(past?"Elapsed":"Remaining",`${days}d ${hours}h ${mins}m`,past?"Target time has passed":"From this device's current time");};},

    "word-counter"(){root.innerHTML=`<div class="tool-form">${textArea("Text","textInput","Start typing or paste text…")}<div id="result"></div></div>`;const run=()=>{const text=val("textInput",root),trim=text.trim(),words=trim?trim.split(/\s+/).length:0,chars=text.length,noSpaces=text.replace(/\s/g,"").length,read=words/200;$("#result",root).innerHTML=resultCard("Words",fmt(words,0),"Live count",`<div class="mini-results">${mini("Characters",fmt(chars,0))}${mini("No spaces",fmt(noSpaces,0))}${mini("Reading",read<1?"< 1 min":`${fmt(read,1)} min`)}${mini("Lines",text?text.split(/\n/).length:0)}</div>`);};$("#textInput",root).oninput=run;run();},
    case(){root.innerHTML=`<div class="tool-form">${textArea("Text","caseInput","Paste text here…")}<div class="action-row"><button class="secondary-button" data-case="upper">UPPER</button><button class="secondary-button" data-case="lower">lower</button><button class="secondary-button" data-case="title">Title</button><button class="secondary-button" data-case="sentence">Sentence</button></div><div class="action-row"><button class="primary-button" id="copyCase">Copy result</button></div></div>`;const apply=mode=>{const el=$("#caseInput",root),s=el.value;if(mode==="upper")el.value=s.toUpperCase();if(mode==="lower")el.value=s.toLowerCase();if(mode==="title")el.value=s.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());if(mode==="sentence")el.value=s.toLowerCase().replace(/(^\s*\w|[.!?]\s+\w)/g,c=>c.toUpperCase());};$$('[data-case]',root).forEach(b=>b.onclick=()=>apply(b.dataset.case));$("#copyCase",root).onclick=()=>copyText(val("caseInput",root));},
    slug(){root.innerHTML=`<div class="tool-form">${textArea("Text","slugInput","My Useful Page Title")}${button("Generate slug")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const out=val("slugInput",root).normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");$("#result",root).innerHTML=resultCard("Slug",out,"Click result to copy");$(".result-card",root).onclick=()=>copyText(out);};},
    "find-replace"(){root.innerHTML=`<div class="tool-form">${textArea("Text","frText","Paste text here…")}<div class="two-col">${field("Find","frFind","text","old text")}${field("Replace with","frReplace","text","new text")}</div>${button("Replace all")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const text=val("frText",root),find=val("frFind",root),rep=val("frReplace",root);if(!find)return;const out=text.split(find).join(rep);$("#result",root).innerHTML=resultCard("Result",out,"Click result to copy");$(".result-card",root).onclick=()=>copyText(out);};},
    "remove-duplicates"(){root.innerHTML=`<div class="tool-form">${textArea("Lines","dupText","apple\nbanana\napple\norange")}${button("Remove duplicates")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const lines=val("dupText",root).split(/\r?\n/),out=[...new Set(lines)].join("\n");$("#result",root).innerHTML=resultCard("Unique lines",out,`${lines.length-[...new Set(lines)].length} duplicate(s) removed`);$(".result-card",root).onclick=()=>copyText(out);};},
    "sort-lines"(){root.innerHTML=`<div class="tool-form">${selectField("Order","sortOrder",[["asc","A → Z"],["desc","Z → A"]])}${textArea("Lines","sortText","pear\napple\nbanana")}${button("Sort")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{let lines=val("sortText",root).split(/\r?\n/);lines.sort((a,b)=>a.localeCompare(b,undefined,{numeric:true,sensitivity:"base"}));if(val("sortOrder",root)==="desc")lines.reverse();const out=lines.join("\n");$("#result",root).innerHTML=resultCard("Sorted text",out,"Click result to copy");$(".result-card",root).onclick=()=>copyText(out);};},
    "trim-lines"(){root.innerHTML=`<div class="tool-form">${textArea("Text","trimText","  first line  \n\n\n second line   ")}${button("Clean text")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const out=val("trimText",root).split(/\r?\n/).map(x=>x.trim()).join("\n").replace(/\n{3,}/g,"\n\n").trim();$("#result",root).innerHTML=resultCard("Cleaned text",out,"Click result to copy");$(".result-card",root).onclick=()=>copyText(out);};},
    "reverse-text"(){root.innerHTML=`<div class="tool-form">${selectField("Reverse","revMode",[["chars","Characters"],["lines","Line order"]])}${textArea("Text","revText","QuickTools")}${button("Reverse")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const s=val("revText",root),out=val("revMode",root)==="chars"?[...s].reverse().join(""):s.split(/\r?\n/).reverse().join("\n");$("#result",root).innerHTML=resultCard("Result",out,"Click result to copy");$(".result-card",root).onclick=()=>copyText(out);};},
    "text-repeat"(){root.innerHTML=`<div class="tool-form">${textArea("Text","repText","Hello")}${field("Times","repN","number","5")}${button("Repeat")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const count=Math.min(1000,Math.max(0,Math.trunc(n("repN",root)||0))),out=Array(count).fill(val("repText",root)).join("\n");$("#result",root).innerHTML=resultCard("Result",out,`${count} repetitions`);$(".result-card",root).onclick=()=>copyText(out);};},
    "reading-time"(){root.innerHTML=`<div class="tool-form">${textArea("Text","readText","Paste text here…")}${button("Estimate")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const words=val("readText",root).trim().split(/\s+/).filter(Boolean).length;$("#result",root).innerHTML=resultCard("Reading time", words ? `${Math.max(1,Math.ceil(words/200))} min` : "0 min", `${words} words · speaking ≈ ${fmt(words/130,1)} min`);};},

    json(){root.innerHTML=`<div class="tool-form">${textArea("JSON","jsonInput",'{"hello":"world"}')}<div class="action-row"><button class="primary-button" id="formatJson">Format</button><button class="secondary-button" id="minifyJson">Minify</button><button class="secondary-button" id="copyJson">Copy</button></div><div id="result"></div></div>`;const transform=space=>{try{const p=JSON.parse(val("jsonInput",root));$("#jsonInput",root).value=JSON.stringify(p,null,space);$("#result",root).innerHTML=resultCard("Status","Valid JSON",space?"Formatted successfully":"Minified successfully");}catch(e){$("#result",root).innerHTML=resultCard("Status","Invalid JSON",e.message);}};$("#formatJson",root).onclick=()=>transform(2);$("#minifyJson",root).onclick=()=>transform(0);$("#copyJson",root).onclick=()=>copyText(val("jsonInput",root));},
    base64(){root.innerHTML=`<div class="tool-form">${selectField("Mode","b64Mode",[["encode","Encode text"],["decode","Decode Base64"]])}${textArea("Input","b64Input","Enter text…")}${button("Convert")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{try{const s=val("b64Input",root),out=val("b64Mode",root)==="encode"?btoa(unescape(encodeURIComponent(s))):decodeURIComponent(escape(atob(s)));$("#result",root).innerHTML=resultCard("Output",out,"Click result to copy");$(".result-card",root).onclick=()=>copyText(out);}catch(e){$("#result",root).innerHTML=resultCard("Output","Invalid input",e.message);}};},
    "url-codec"(){root.innerHTML=`<div class="tool-form">${selectField("Mode","urlMode",[["encode","Encode component"],["decode","Decode component"]])}${textArea("Input","urlInput","hello world?x=1")}${button("Convert")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{try{const out=val("urlMode",root)==="encode"?encodeURIComponent(val("urlInput",root)):decodeURIComponent(val("urlInput",root));$("#result",root).innerHTML=resultCard("Output",out,"Click result to copy");$(".result-card",root).onclick=()=>copyText(out);}catch(e){$("#result",root).innerHTML=resultCard("Output","Invalid encoding",e.message);}};},
    "html-entities"(){root.innerHTML=`<div class="tool-form">${selectField("Mode","htmlMode",[["escape","Escape HTML"],["unescape","Unescape HTML"]])}${textArea("Input","htmlInput","<strong>Hello</strong>")}${button("Convert")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{let out;if(val("htmlMode",root)==="escape")out=escapeHTML(val("htmlInput",root));else{const ta=document.createElement("textarea");ta.innerHTML=val("htmlInput",root);out=ta.value;}$("#result",root).innerHTML=resultCard("Output",out,"Click result to copy");$(".result-card",root).onclick=()=>copyText(out);};},
    "number-base"(){root.innerHTML=`<div class="tool-form">${selectField("From base","baseFrom",[["2","Binary"],["8","Octal"],["10","Decimal"],["16","Hexadecimal"]])}${field("Value","baseValue","text","FF")}${button("Convert")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const base=Number(val("baseFrom",root)),x=parseInt(val("baseValue",root).trim(),base);if(!Number.isFinite(x))return;$("#result",root).innerHTML=resultCard("Decimal",String(x),"All bases",`<div class="mini-results">${mini("Binary",x.toString(2))}${mini("Octal",x.toString(8))}${mini("Hex",x.toString(16).toUpperCase())}</div>`);};},
    "color-converter"(){root.innerHTML=`<div class="tool-form">${selectField("Mode","colorMode",[["hex","HEX → RGB"],["rgb","RGB → HEX"]])}<div id="colorFields"></div>${button("Convert")}<div id="result"></div></div>`;const render=()=>{$("#colorFields",root).innerHTML=val("colorMode",root)==="hex"?field("HEX","hexValue","text","#3366FF"):`<div class="two-col">${field("Red","red","number","51")}${field("Green","green","number","102")}${field("Blue","blue","number","255")}</div>`;};render();$("#colorMode",root).onchange=render;$("#runTool",root).onclick=()=>{if(val("colorMode",root)==="hex"){let h=val("hexValue",root).replace("#","").trim();if(h.length===3)h=[...h].map(c=>c+c).join("");if(!/^[0-9a-fA-F]{6}$/.test(h))return;const nums=[0,2,4].map(i=>parseInt(h.slice(i,i+2),16));$("#result",root).innerHTML=resultCard("RGB",`rgb(${nums.join(", ")})`,`#${h.toUpperCase()}`);}else{const rgb=[n("red",root),n("green",root),n("blue",root)].map(x=>Math.max(0,Math.min(255,Math.round(x))));if(!rgb.every(Number.isFinite))return;const h="#"+rgb.map(x=>x.toString(16).padStart(2,"0")).join("").toUpperCase();$("#result",root).innerHTML=resultCard("HEX",h,`rgb(${rgb.join(", ")})`);}};},
    sha256(){root.innerHTML=`<div class="tool-form">${textArea("Text","hashInput","hello world")}${button("Generate hash")}<div id="result"></div></div>`;$("#runTool",root).onclick=async()=>{const data=new TextEncoder().encode(val("hashInput",root)),buf=await crypto.subtle.digest("SHA-256",data),out=[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,"0")).join("");$("#result",root).innerHTML=resultCard("SHA-256",out,"Click result to copy");$(".result-card",root).onclick=()=>copyText(out);};},
    uuid(){root.innerHTML=`<div class="tool-form">${button("Generate UUID")}<div id="result"></div></div>`;const run=()=>{const out=crypto.randomUUID?crypto.randomUUID():"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,c=>{const r=crypto.getRandomValues(new Uint8Array(1))[0]%16,v=c==="x"?r:(r&3|8);return v.toString(16);});$("#result",root).innerHTML=resultCard("UUID v4",out,"Click result to copy");$(".result-card",root).onclick=()=>copyText(out);};$("#runTool",root).onclick=run;run();},
    jwt(){root.innerHTML=`<div class="tool-form">${textArea("JWT","jwtInput","Paste a JSON Web Token…")}${button("Decode")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{try{const parts=val("jwtInput",root).trim().split(".");if(parts.length<2)throw new Error("JWT must have at least two segments.");const decode=p=>JSON.parse(decodeURIComponent(escape(atob(p.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(p.length/4)*4,"=")))));const h=decode(parts[0]),p=decode(parts[1]),out=JSON.stringify({header:h,payload:p},null,2);$("#result",root).innerHTML=resultCard("Decoded",out,"Signature is not verified by this tool.");$(".result-card",root).onclick=()=>copyText(out);}catch(e){$("#result",root).innerHTML=resultCard("Decoded","Invalid JWT",e.message);}};},

    password(){root.innerHTML=`<div class="tool-form">${field("Length","pwLength","number","20","characters")}<div class="two-col">${selectField("Numbers","pwNumbers",[["yes","Include"],["no","Exclude"]])}${selectField("Symbols","pwSymbols",[["yes","Include"],["no","Exclude"]])}</div>${button("Generate password")}<div id="result"></div></div>`;const run=()=>{const len=Math.min(128,Math.max(4,Math.trunc(n("pwLength",root)||20)));let chars="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";if(val("pwNumbers",root)==="yes")chars+="0123456789";if(val("pwSymbols",root)==="yes")chars+="!@#$%^&*()-_=+[]{}?";const arr=new Uint32Array(len);crypto.getRandomValues(arr);const out=[...arr].map(x=>chars[x%chars.length]).join("");$("#result",root).innerHTML=resultCard("Generated password",out,"Click result to copy");$(".result-card",root).onclick=()=>copyText(out);};$("#runTool",root).onclick=run;run();},
    random(){root.innerHTML=`<div class="tool-form"><div class="two-col">${field("Minimum","randMin","number","1")}${field("Maximum","randMax","number","100")}</div>${button("Generate number")}<div id="result"></div></div>`;const run=()=>{let min=Math.ceil(n("randMin",root)),max=Math.floor(n("randMax",root));if(!validNumbers(min,max))return;if(min>max)[min,max]=[max,min];const range=max-min+1,a=new Uint32Array(1);crypto.getRandomValues(a);const out=min+(a[0]%range);$("#result",root).innerHTML=resultCard("Random number",String(out),`Between ${min} and ${max}`);};$("#runTool",root).onclick=run;run();},
    "random-list"(){root.innerHTML=`<div class="tool-form">${textArea("Items — one per line","pickList","Apple\nBanana\nOrange")}${button("Pick one")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const xs=val("pickList",root).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!xs.length)return;const a=new Uint32Array(1);crypto.getRandomValues(a);$("#result",root).innerHTML=resultCard("Selected item",xs[a[0]%xs.length],`${xs.length} choices`);};},
    coin(){root.innerHTML=`<div class="tool-form">${button("Flip coin")}<div id="result"></div></div>`;const run=()=>{const a=new Uint8Array(1);crypto.getRandomValues(a);$("#result",root).innerHTML=resultCard("Coin flip",a[0]%2?"Heads":"Tails");};$("#runTool",root).onclick=run;run();},
    dice(){simpleTool(root,`<div class="two-col">${field("Number of dice","diceN","number","2")}${field("Sides per die","diceS","number","6")}</div>`,()=>{const count=Math.min(50,Math.max(1,Math.trunc(n("diceN",root)))),sides=Math.min(1000,Math.max(2,Math.trunc(n("diceS",root))));const arr=new Uint32Array(count);crypto.getRandomValues(arr);const rolls=[...arr].map(x=>x%sides+1);return{value:String(rolls.reduce((a,b)=>a+b,0)),note:`Rolls: ${rolls.join(", ")}`};});},
    pin(){root.innerHTML=`<div class="tool-form">${field("Digits","pinLen","number","6")}${button("Generate PIN")}<div id="result"></div></div>`;const run=()=>{const len=Math.min(20,Math.max(3,Math.trunc(n("pinLen",root)||6))),a=new Uint8Array(len);crypto.getRandomValues(a);const out=[...a].map(x=>x%10).join("");$("#result",root).innerHTML=resultCard("PIN",out,"Generated locally with browser crypto");};$("#runTool",root).onclick=run;run();},
    lorem(){root.innerHTML=`<div class="tool-form">${field("Paragraphs","loremN","number","3")}${button("Generate text")}<div id="result"></div></div>`;$("#runTool",root).onclick=()=>{const base="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Curabitur blandit tempus porttitor. Maecenas faucibus mollis interdum. Donec id elit non mi porta gravida at eget metus.";const count=Math.min(20,Math.max(1,Math.trunc(n("loremN",root)||3))),out=Array(count).fill(base).join("\n\n");$("#result",root).innerHTML=resultCard("Lorem ipsum",out,"Click result to copy");$(".result-card",root).onclick=()=>copyText(out);};},
    "random-color"(){root.innerHTML=`<div class="tool-form">${button("Generate color")}<div id="result"></div></div>`;const run=()=>{const a=new Uint8Array(3);crypto.getRandomValues(a);const hex="#"+[...a].map(x=>x.toString(16).padStart(2,"0")).join("").toUpperCase();$("#result",root).innerHTML=resultCard("Color",hex,`rgb(${[...a].join(", ")})`,`<div style="height:72px;border-radius:14px;margin-top:14px;background:${hex};border:1px solid var(--line)"></div>`);$(".result-card",root).onclick=()=>copyText(hex);};$("#runTool",root).onclick=run;run();}
  };
  handlers[id]?.();
}

window.QuickTools={tools,renderToolUI,toolSlug,categorySlug};

const storedTheme=localStorage.getItem("quicktools-theme");if(storedTheme)document.documentElement.dataset.theme=storedTheme;
const themeToggle=$("#themeToggle");if(themeToggle)themeToggle.addEventListener("click",()=>{const next=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=next;localStorage.setItem("quicktools-theme",next);});
const yearEl=$("#year");if(yearEl)yearEl.textContent=new Date().getFullYear();

if(search&&grid&&categoryTabs&&emptyState){
  search.addEventListener("input",()=>{searchTerm=search.value;renderTools();});
  const toolCountEl=$("#toolCount");if(toolCountEl)toolCountEl.textContent=tools.length;
  const sectionCount=$("#sectionToolCount");if(sectionCount)sectionCount.textContent=tools.length;
  renderTabs();renderTools();renderQuickLinks();
  const initialTool=location.hash.replace("#","");
  const legacyTool=tools.find(t=>t.id===initialTool);
  if(legacyTool) location.replace(`tools/${toolSlug(legacyTool)}/`);
}

const pageToolRoot=$("#toolPageApp");
if(pageToolRoot){
  const toolId=document.body.dataset.toolPage;
  const tool=tools.find(t=>t.id===toolId);
  if(tool){
    pageToolRoot.closest(".tool-workspace")?.setAttribute("data-cat",categorySlug(tool.category));
    renderToolUI(toolId,pageToolRoot);
  }
}
